"""Seed the database with ~30 sample book nodes forming a tree."""
from django.core.management.base import BaseCommand
from tree.models import Node, Edge


SAMPLE_BOOKS = [
    # Root anchor nodes (genre hubs)
    {
        "title": "Science Fiction",
        "node_type": "genre",
        "genre": "Science Fiction",
        "style": {"color": "#1a3a5c", "glow": "#4fc3f7"},
        "parent": None,
        "_key": "sci_fi",
    },
    {
        "title": "Fantasy",
        "node_type": "genre",
        "genre": "Fantasy",
        "style": {"color": "#2d1b4e", "glow": "#ce93d8"},
        "parent": None,
        "_key": "fantasy",
    },
    {
        "title": "Classic Literature",
        "node_type": "genre",
        "genre": "Classic",
        "style": {"color": "#1b3a2d", "glow": "#a5d6a7"},
        "parent": None,
        "_key": "classic",
    },
    # Sci-Fi branch
    {
        "title": "Neuromancer",
        "node_type": "book",
        "author": "William Gibson",
        "genre": "Science Fiction",
        "year": 1984,
        "isbn": "9780441569595",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg",
        "rating": 4.5,
        "badges": ["⭐"],
        "style": {"color": "#0d2137"},
        "parent": "sci_fi",
        "_key": "neuromancer",
    },
    {
        "title": "Dune",
        "node_type": "book",
        "author": "Frank Herbert",
        "genre": "Science Fiction",
        "year": 1965,
        "isbn": "9780441013593",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg",
        "rating": 4.8,
        "badges": ["⭐", "🔥"],
        "style": {"color": "#2a1800"},
        "parent": "sci_fi",
        "_key": "dune",
    },
    {
        "title": "Foundation",
        "node_type": "book",
        "author": "Isaac Asimov",
        "genre": "Science Fiction",
        "year": 1951,
        "isbn": "9780553293357",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
        "rating": 4.6,
        "badges": ["📚"],
        "style": {"color": "#1a1a2e"},
        "parent": "sci_fi",
        "_key": "foundation",
    },
    {
        "title": "1984",
        "node_type": "book",
        "author": "George Orwell",
        "genre": "Science Fiction",
        "year": 1949,
        "isbn": "9780451524935",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
        "rating": 4.7,
        "badges": ["🔥"],
        "style": {"color": "#1c1c1c"},
        "parent": "sci_fi",
        "_key": "1984",
    },
    {
        "title": "The Martian",
        "node_type": "book",
        "author": "Andy Weir",
        "genre": "Science Fiction",
        "year": 2011,
        "isbn": "9780553418026",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780553418026-L.jpg",
        "rating": 4.4,
        "badges": [],
        "style": {"color": "#3b0a00"},
        "parent": "neuromancer",
        "_key": "martian",
    },
    {
        "title": "Ender's Game",
        "node_type": "book",
        "author": "Orson Scott Card",
        "genre": "Science Fiction",
        "year": 1985,
        "isbn": "9780812550702",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780812550702-L.jpg",
        "rating": 4.5,
        "badges": ["⭐"],
        "style": {"color": "#002244"},
        "parent": "foundation",
        "_key": "enders_game",
    },
    {
        "title": "The Expanse",
        "node_type": "series",
        "author": "James S.A. Corey",
        "genre": "Science Fiction",
        "style": {"color": "#0a1628", "glow": "#29b6f6"},
        "parent": "dune",
        "_key": "expanse_series",
    },
    {
        "title": "Leviathan Wakes",
        "node_type": "book",
        "author": "James S.A. Corey",
        "genre": "Science Fiction",
        "year": 2011,
        "isbn": "9780316129084",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780316129084-L.jpg",
        "rating": 4.3,
        "badges": ["📚"],
        "style": {"color": "#0a1628"},
        "parent": "expanse_series",
        "_key": "leviathan",
    },
    # Fantasy branch
    {
        "title": "The Hobbit",
        "node_type": "book",
        "author": "J.R.R. Tolkien",
        "genre": "Fantasy",
        "year": 1937,
        "isbn": "9780261102217",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780261102217-L.jpg",
        "rating": 4.7,
        "badges": ["⭐", "🔥"],
        "style": {"color": "#1a3300"},
        "parent": "fantasy",
        "_key": "hobbit",
    },
    {
        "title": "The Lord of the Rings",
        "node_type": "series",
        "author": "J.R.R. Tolkien",
        "genre": "Fantasy",
        "style": {"color": "#14291a", "glow": "#66bb6a"},
        "parent": "hobbit",
        "_key": "lotr",
    },
    {
        "title": "The Fellowship of the Ring",
        "node_type": "book",
        "author": "J.R.R. Tolkien",
        "genre": "Fantasy",
        "year": 1954,
        "isbn": "9780261102354",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780261102354-L.jpg",
        "rating": 4.8,
        "badges": ["⭐"],
        "style": {"color": "#14291a"},
        "parent": "lotr",
        "_key": "fotr",
    },
    {
        "title": "Mistborn",
        "node_type": "book",
        "author": "Brandon Sanderson",
        "genre": "Fantasy",
        "year": 2006,
        "isbn": "9780765311788",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780765311788-L.jpg",
        "rating": 4.6,
        "badges": ["🔥"],
        "style": {"color": "#2d1b00"},
        "parent": "fantasy",
        "_key": "mistborn",
    },
    {
        "title": "The Way of Kings",
        "node_type": "book",
        "author": "Brandon Sanderson",
        "genre": "Fantasy",
        "year": 2010,
        "isbn": "9780765326355",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780765326355-L.jpg",
        "rating": 4.7,
        "badges": ["⭐", "📚"],
        "style": {"color": "#1a0d2e"},
        "parent": "mistborn",
        "_key": "way_of_kings",
    },
    {
        "title": "The Name of the Wind",
        "node_type": "book",
        "author": "Patrick Rothfuss",
        "genre": "Fantasy",
        "year": 2007,
        "isbn": "9780756404741",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
        "rating": 4.5,
        "badges": ["⭐"],
        "style": {"color": "#0d1f2d"},
        "parent": "fantasy",
        "_key": "name_of_wind",
    },
    {
        "title": "A Wizard of Earthsea",
        "node_type": "book",
        "author": "Ursula K. Le Guin",
        "genre": "Fantasy",
        "year": 1968,
        "isbn": "9780547773742",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780547773742-L.jpg",
        "rating": 4.2,
        "badges": [],
        "style": {"color": "#003344"},
        "parent": "name_of_wind",
        "_key": "earthsea",
    },
    # Classics branch
    {
        "title": "Pride and Prejudice",
        "node_type": "book",
        "author": "Jane Austen",
        "genre": "Classic",
        "year": 1813,
        "isbn": "9780141439518",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
        "rating": 4.5,
        "badges": ["⭐"],
        "style": {"color": "#2c1810"},
        "parent": "classic",
        "_key": "pride_prejudice",
    },
    {
        "title": "Moby-Dick",
        "node_type": "book",
        "author": "Herman Melville",
        "genre": "Classic",
        "year": 1851,
        "isbn": "9780142437247",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg",
        "rating": 3.9,
        "badges": [],
        "style": {"color": "#001a33"},
        "parent": "classic",
        "_key": "moby_dick",
    },
    {
        "title": "Crime and Punishment",
        "node_type": "book",
        "author": "Fyodor Dostoevsky",
        "genre": "Classic",
        "year": 1866,
        "isbn": "9780140449136",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780140449136-L.jpg",
        "rating": 4.4,
        "badges": ["🔥"],
        "style": {"color": "#1a0000"},
        "parent": "classic",
        "_key": "crime_punishment",
    },
    {
        "title": "To Kill a Mockingbird",
        "node_type": "book",
        "author": "Harper Lee",
        "genre": "Classic",
        "year": 1960,
        "isbn": "9780061935466",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780061935466-L.jpg",
        "rating": 4.6,
        "badges": ["⭐"],
        "style": {"color": "#1a2400"},
        "parent": "pride_prejudice",
        "_key": "mockingbird",
    },
    {
        "title": "The Great Gatsby",
        "node_type": "book",
        "author": "F. Scott Fitzgerald",
        "genre": "Classic",
        "year": 1925,
        "isbn": "9780743273565",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
        "rating": 4.0,
        "badges": [],
        "style": {"color": "#1a1500"},
        "parent": "moby_dick",
        "_key": "gatsby",
    },
    # Cross-genre / deep leaves
    {
        "title": "Brave New World",
        "node_type": "book",
        "author": "Aldous Huxley",
        "genre": "Science Fiction",
        "year": 1932,
        "isbn": "9780060850524",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
        "rating": 4.2,
        "badges": ["🔥"],
        "style": {"color": "#14002a"},
        "parent": "1984",
        "_key": "brave_new_world",
    },
    {
        "title": "Fahrenheit 451",
        "node_type": "book",
        "author": "Ray Bradbury",
        "genre": "Science Fiction",
        "year": 1953,
        "isbn": "9781451673319",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg",
        "rating": 4.3,
        "badges": ["🔥"],
        "style": {"color": "#2a0800"},
        "parent": "brave_new_world",
        "_key": "fahrenheit",
    },
    {
        "title": "Slaughterhouse-Five",
        "node_type": "book",
        "author": "Kurt Vonnegut",
        "genre": "Science Fiction",
        "year": 1969,
        "isbn": "9780385333849",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780385333849-L.jpg",
        "rating": 4.3,
        "badges": [],
        "style": {"color": "#1a1500"},
        "parent": "fahrenheit",
        "_key": "slaughterhouse",
    },
    {
        "title": "American Gods",
        "node_type": "book",
        "author": "Neil Gaiman",
        "genre": "Fantasy",
        "year": 2001,
        "isbn": "9780380973651",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780380973651-L.jpg",
        "rating": 4.3,
        "badges": ["⭐"],
        "style": {"color": "#0d0d1a"},
        "parent": "earthsea",
        "_key": "american_gods",
    },
    {
        "title": "Good Omens",
        "node_type": "book",
        "author": "Terry Pratchett & Neil Gaiman",
        "genre": "Fantasy",
        "year": 1990,
        "isbn": "9780060853976",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780060853976-L.jpg",
        "rating": 4.4,
        "badges": ["⭐"],
        "style": {"color": "#1a0a00"},
        "parent": "american_gods",
        "_key": "good_omens",
    },
    {
        "title": "Anna Karenina",
        "node_type": "book",
        "author": "Leo Tolstoy",
        "genre": "Classic",
        "year": 1877,
        "isbn": "9780140449174",
        "cover_image": "https://covers.openlibrary.org/b/isbn/9780140449174-L.jpg",
        "rating": 4.5,
        "badges": [],
        "style": {"color": "#2a1a00"},
        "parent": "crime_punishment",
        "_key": "anna_karenina",
    },
]


class Command(BaseCommand):
    help = "Seed the database with ~30 sample book nodes"

    def handle(self, *args, **options):
        Node.objects.all().delete()
        Edge.objects.all().delete()

        self.stdout.write("Seeding nodes...")

        key_map = {}  # _key -> saved Node instance

        for book in SAMPLE_BOOKS:
            parent_key = book.pop("parent", None)
            key = book.pop("_key")

            parent_node = key_map.get(parent_key) if parent_key else None

            node = Node(
                title=book["title"],
                node_type=book.get("node_type", "book"),
                author=book.get("author", ""),
                genre=book.get("genre", ""),
                year=book.get("year"),
                isbn=book.get("isbn", ""),
                cover_image=book.get("cover_image", ""),
                rating=book.get("rating"),
                badges=book.get("badges", []),
                style=book.get("style", {}),
                parent=parent_node,
            )
            node.save()
            key_map[key] = node

        self.stdout.write(self.style.SUCCESS(f"Seeded {len(key_map)} nodes."))
