# Generated by Django 6.0.3 on 2026-03-05 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('book', 'Book'), ('author', 'Author'), ('genre', 'Genre'), ('series', 'Series'), ('custom', 'Custom')], default='book', max_length=20)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('cover_image', models.URLField(blank=True, max_length=1000)),
                ('cover_upload', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('pos_x', models.FloatField(blank=True, null=True)),
                ('pos_y', models.FloatField(blank=True, null=True)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_read', models.DateField(blank=True, null=True)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tree.node')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('progression', 'Reading Progression'), ('genre', 'Same Genre'), ('author', 'Same Author'), ('series', 'Same Series'), ('custom', 'Custom')], default='progression', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='tree.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='tree.node')),
            ],
            options={
                'unique_together': {('source', 'target', 'edge_type')},
            },
        ),
    ]
