# Generated by Django 6.0.3 on 2026-05-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_community_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendrequest',
            new_name='tree_friend_to_user_5d2a1e_idx',
            old_name='tree_friend_to_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='friendrequest',
            new_name='tree_friend_from_us_f82768_idx',
            old_name='tree_friend_from_user_status_idx',
        ),
    ]
