# Generated by Django 4.2.29 on 2026-05-17 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0005_node_shelves'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='tree_version_user_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('goodreads', 'Goodreads')], default='goodreads', max_length=32)),
                ('source_key', models.CharField(blank=True, max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('cover_image', models.URLField(blank=True, max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_read', models.DateField(blank=True, null=True)),
                ('shelf', models.CharField(choices=[('all', 'All'), ('want_to_read', 'Want to Read'), ('currently_reading', 'Currently Reading'), ('read', 'Read'), ('did_not_finish', 'Did Not Finish')], default='want_to_read', max_length=32)),
                ('custom_shelf', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_added'],
                'indexes': [models.Index(fields=['user', 'source', 'date_added'], name='import_book_user_src_idx'), models.Index(fields=['user', 'isbn'], name='import_book_user_isbn_idx')],
            },
        ),
    ]
