# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0011_bookreview_tree_visibility_community_tree_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_symbol',
            field=models.CharField(
                choices=[
                    ('🌲', 'Evergreen'),
                    ('🌳', 'Oak'),
                    ('🌱', 'Sapling'),
                    ('🌴', 'Palm'),
                    ('🍁', 'Autumn'),
                    ('🌸', 'Bloom'),
                ],
                default='🌲',
                max_length=8,
            ),
        ),
    ]
