# Generated by Codex on 2026-07-03

from django.conf import settings
from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('tree', 'UserProfile')
    symbols = ['🌲', '🌳', '🌱', '🌴', '🍁', '🌸']

    existing_user_ids = set(UserProfile.objects.values_list('user_id', flat=True))
    profiles = []
    for user in User.objects.order_by('id'):
        if user.id in existing_user_ids:
            continue
        profiles.append(
            UserProfile(
                user_id=user.id,
                display_name='',
                bio='',
                avatar_url='',
                avatar_symbol=symbols[user.id % len(symbols)],
            )
        )
    if profiles:
        UserProfile.objects.bulk_create(profiles)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0012_userprofile_avatar_symbol'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
