from django.urls import path
from . import views

app_name = 'tree'

urlpatterns = [
    # Pages
    path('', views.landing, name='landing'),
    path('community/', views.community_feed, name='community-feed'),
    path('community/my-posts/', views.community_my_posts, name='community-my-posts'),
    path('community/new/', views.community_create_post, name='community-create-post'),
    path('community/my-posts/<int:post_id>/edit/', views.community_edit_post, name='community-edit-post'),
    path('community/my-posts/<int:post_id>/delete/', views.community_delete_post, name='community-delete-post'),
    path('community/people/', views.community_people, name='community-people'),
    path('community/requests/', views.community_requests, name='community-requests'),
    path('community/friends/', views.community_friends, name='community-friends'),
    path('community/request/send/<int:user_id>/', views.send_friend_request, name='community-send-request'),
    path('community/request/<int:request_id>/accept/', views.accept_friend_request, name='community-accept-request'),
    path('community/request/<int:request_id>/reject/', views.reject_friend_request, name='community-reject-request'),
    path('register/', views.register_view, name='register'),
    path('verify-email/<uidb64>/<token>/', views.verify_email_view, name='verify-email'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('tree/', views.tree_page, name='tree'),
    path('users/<str:username>/trees/<int:tree_id>/', views.shared_tree_page, name='shared-tree'),
    path('my-books/', views.my_books, name='my-books'),
    path('challenges/', views.challenges, name='challenges'),
    path('book/', views.book_page, name='book'),

    # API
    path('api/tree/', views.tree_data, name='api-tree'),
    path('api/shared-tree/<str:username>/<int:tree_id>/', views.shared_tree_data, name='api-shared-tree'),
    path('api/trees/', views.tree_list, name='api-tree-list'),
    path('api/trees/<int:tree_id>/', views.tree_detail, name='api-tree-detail'),
    path('api/tree/versions/', views.tree_version_list, name='api-tree-versions'),
    path('api/tree/versions/save/', views.tree_version_create, name='api-tree-version-create'),
    path('api/tree/versions/<int:version_id>/restore/', views.tree_version_restore, name='api-tree-version-restore'),
    path('api/tree/discard/', views.tree_snapshot_restore, name='api-tree-discard'),
    path('api/tree/auto-from-shelf/', views.tree_auto_from_shelf, name='api-tree-auto-from-shelf'),
    path('api/nodes/', views.node_list, name='api-node-list'),
    path('api/nodes/<str:pk>/', views.node_detail, name='api-node-detail'),
    path('api/my-books/', views.library_book_create, name='api-my-books-create'),
    path('api/book-reviews/', views.book_review_list_create, name='api-book-reviews'),
    path('api/book-reviews/<int:review_id>/', views.book_review_detail, name='api-book-review-detail'),
    path('api/my-books/recommendations/', views.my_books_recommendations, name='api-my-books-recommendations'),
    path('api/imported-books/<int:pk>/', views.imported_book_detail, name='api-imported-book-detail'),
    path('api/imported-books/<int:pk>/add-to-tree/', views.imported_book_add_to_tree, name='api-imported-book-add-to-tree'),
    path('api/edges/', views.edge_list, name='api-edge-list'),
    path('api/edges/<str:pk>/', views.edge_detail, name='api-edge-detail'),
    path('api/cover/', views.fetch_cover, name='api-cover'),
    path('api/book-search/', views.search_books, name='api-book-search'),
    path('api/critic-reviews/', views.critic_reviews, name='api-critic-reviews'),
    path('api/author-search/', views.search_authors, name='api-author-search'),
    path('api/challenges/target/', views.challenge_target_update, name='api-challenge-target'),
    path('api/reading-updates/', views.reading_update_create, name='api-reading-update'),
    path('api/goodreads/preview/', views.goodreads_import_preview, name='api-goodreads-preview'),
    path('api/goodreads/import/', views.goodreads_import_confirm, name='api-goodreads-import'),
]
